apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #  push: false
  googleCloudBuild: #gcloud
    projectId: ticketing-dev-324816 #gcloud
  artifacts:
    #- image: dyrektorek/auth
    - image: us.gcr.io/ticketing-dev-324816/auth #gcloud
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: . # throw the changed file into the same folder as the src
