apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # watch all of these files
build:
  local:
    push: false #do not docker push the files
  artifacts:
    - image: dyrektorek/client
      context: client # needs to maintain that folder (update pods)
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js" # if there are changes to other filetypes - it will rebuild the image dyrektorek/client
            dest: .
    - image: dyrektorek/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: dyrektorek/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: dyrektorek/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: dyrektorek/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: dyrektorek/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
