name: tests-payments

on:
  pull_request:
    paths:
      - "microservices/ticketing/payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd microservices/ticketing/payments && npm install && npm run test:ci
